import { eq, and, or, ne, gte, lte, like, inArray, desc, asc, count, sql, lt, gt } from "drizzle-orm";
import { db, areas, siteLogs, chillerReadings, logMaster } from "../database";
import logger from "../utils/logger";
import { startOfDay, endOfDay, format, addDays } from "date-fns";
import NetInfo from "@react-native-community/netinfo";
import { apiFetch as centralApiFetch } from "../utils/apiHelper";
import { API_BASE_URL } from "../constants/api";

const _apiFetch = async (endpoint: string) => {
  return centralApiFetch(`${API_BASE_URL}${endpoint}`);
};

export interface TaskItem {
  id: string;
  name: string;
  type: "area" | "asset" | "general";
  isCompleted: boolean;
  status: "Open" | "Inprogress" | "Completed";
  lastLogId?: string;
  meta?: any;
}

/**
 * Helper: get the canonical log_name variants for fuzzy matching.
 * The server may store "Temp & Humidity" while mobile uses "Temp RH", etc.
 */
function getLogVariants(logName: string): string[] {
  const lower = logName.toLowerCase();
  if (lower.includes("temp") || lower.includes("rh")) {
    return ["Temp RH", "Temp & Humidity", "Temperature & Humidity", "Temp/RH"];
  }
  if (lower.includes("water")) {
    return ["Water", "Water Monitoring", "Water Analysis", "Water Parameters", "Water Logs", "Raw Water Monitoring"];
  }
  if (lower.includes("chemical")) {
    return ["Chemical Dosing", "Chemical Monitoring", "Chemical Analysis", "Chemicals", "Cooling Tower Chemical Dosing"];
  }
  return [logName];
}

export const SiteConfigService = {
  /**
   * Get pending (non-Completed) tasks for a site/date/log type.
   *
   * Records are PRE-GENERATED by the backend. We simply query the local
   * site_logs table — no template generation needed.
   *
   * Query:
   *   SELECT * FROM site_logs
   *   WHERE site_code = :siteCode
   *     AND scheduled_date = :date
   *     AND status != 'Completed'
   *     AND log_name IN (:variants)
   *     [AND remarks LIKE '%shift%']  -- Temp RH only
   */
  async getPendingTasks(
    siteCode: string,
    logName: string,
    targetDate: string,
    shift?: string
  ): Promise<TaskItem[]> {
    try {
      const logVariants = getLogVariants(logName);

      // Build conditions
      const conditions = [
        eq(siteLogs.site_code, siteCode),
        inArray(siteLogs.log_name, logVariants),
        ne(siteLogs.status, "Completed"),
        sql`substr(${siteLogs.scheduled_date}, 1, 10) = ${targetDate}`,
      ];

      // Shift filter for Temp RH
      const shiftMarker = shift === "A" ? "1/3" : shift === "B" ? "2/3" : shift === "C" ? "3/3" : null;
      if (shiftMarker) {
        conditions.push(like(siteLogs.remarks, `%${shiftMarker}%`));
      }

      const rows = await db
        .select()
        .from(siteLogs)
        .where(and(...conditions))
        .orderBy(asc(siteLogs.task_name));

      // Map to TaskItem[]
      return rows.map(log => ({
        id: log.id,
        name: log.task_name?.trim() || "Unnamed Task",
        type: "area" as const,
        isCompleted: false,
        status: (log.status as "Open" | "Inprogress") || "Open",
        lastLogId: log.id,
        meta: { ...log, scheduled_date: targetDate },
      }));
    } catch (error: any) {
      logger.error("Error in getPendingTasks", { siteCode, error: error.message });
      return [];
    }
  },

  /**
   * Get ALL tasks (including completed) for a site/date/log type.
   * Used by getCategoryProgress for counts.
   */
  async getLogTasks(
    siteCode: string,
    logName: string,
    fromDate?: Date | null,
    toDate?: Date | null,
    shift?: string,
    countOnly = false,
    targetDate?: string,
  ): Promise<TaskItem[]> {
    try {
      const scheduledDateStr = targetDate || format(startOfDay(fromDate || new Date()), "yyyy-MM-dd");
      const logVariants = getLogVariants(logName);

      logger.info(`Fetching tasks for ${siteCode} / ${logName} on ${scheduledDateStr}`, { shift });

      // Build conditions
      const conditions = [
        eq(siteLogs.site_code, siteCode),
        inArray(siteLogs.log_name, logVariants),
        sql`substr(${siteLogs.scheduled_date}, 1, 10) = ${scheduledDateStr}`,
      ];

      const shiftMarker = shift === "A" ? "1/3" : shift === "B" ? "2/3" : shift === "C" ? "3/3" : null;
      if (shiftMarker) {
        conditions.push(like(siteLogs.remarks, `%${shiftMarker}%`));
      }

      const rows = await db
        .select()
        .from(siteLogs)
        .where(and(...conditions))
        .orderBy(asc(siteLogs.task_name));

      return rows.map(log => ({
        id: log.id,
        name: log.task_name?.trim() || "Unnamed Task",
        type: "area" as const,
        isCompleted: log.status?.toLowerCase() === "completed",
        status: (log.status as "Open" | "Inprogress" | "Completed") || "Open",
        lastLogId: log.id,
        meta: { ...log, scheduled_date: scheduledDateStr },
      }));
    } catch (error: any) {
      logger.error("Error in getLogTasks", { siteCode, error: error.message });
      return [];
    }
  },

  /**
   * Chiller tasks — NOT pre-generated, uses chiller_readings table.
   * This logic is UNCHANGED.
   */
  async getChillerTasks(siteCode: string, fromDate?: Date | null, toDate?: Date | null): Promise<TaskItem[]> {
    try {
      const recentReadings = await db
        .select()
        .from(chillerReadings)
        .where(eq(chillerReadings.site_code, siteCode))
        .orderBy(desc(chillerReadings.created_at))
        .limit(50);

      const uniqueChillers = new Set<string>();
      recentReadings.forEach((r) => { if (r.chiller_id) uniqueChillers.add(r.chiller_id); });

      if (uniqueChillers.size === 0) {
        const fallbackChillers = await db
          .select()
          .from(areas)
          .where(and(eq(areas.site_code, siteCode), like(areas.asset_name, "%Chiller%")));
        if (fallbackChillers.length > 0) {
          fallbackChillers.forEach(a => uniqueChillers.add(a.asset_name));
        } else {
          const siteHasAreasResult = await db.select({ value: count() }).from(areas).where(eq(areas.site_code, siteCode));
          if ((siteHasAreasResult[0]?.value ?? 0) > 0) {
            const masterChillers = await db.select().from(logMaster).where(like(logMaster.log_name, "%Chiller%"));
            masterChillers.forEach(m => { if (m.task_name) uniqueChillers.add(m.task_name); });
          }
        }
      }

      const start = fromDate ? startOfDay(fromDate).getTime() : startOfDay(new Date()).getTime();
      const end = toDate ? endOfDay(toDate).getTime() : endOfDay(new Date()).getTime();

      const timeframeReadings = await db
        .select()
        .from(chillerReadings)
        .where(
          and(
            eq(chillerReadings.site_code, siteCode),
            or(ne(chillerReadings.status, "Completed"), and(gte(chillerReadings.reading_time, start), lte(chillerReadings.reading_time, end)))
          )
        )
        .orderBy(desc(chillerReadings.reading_time));

      const finalTasks: TaskItem[] = [];
      const templateChillerIdsObserved = new Set<string>();

      timeframeReadings.forEach((reading) => {
        const chillerId = reading.chiller_id;
        if (!chillerId) return;
        let status: any = (reading.status || "").toLowerCase().replace(/\s/g, "");
        if (status === "completed" || !reading.status) status = "Completed";
        else if (status === "inprogress") status = "Inprogress";
        else status = "Open";

        if (status === "Completed") {
          if (!templateChillerIdsObserved.has(chillerId)) {
            finalTasks.push({ id: reading.id, name: chillerId, type: "asset", isCompleted: true, status: "Completed" });
            templateChillerIdsObserved.add(chillerId);
          }
        } else {
          finalTasks.push({ id: reading.id, name: chillerId, type: "asset", isCompleted: false, status: status });
          templateChillerIdsObserved.add(chillerId);
        }
      });

      uniqueChillers.forEach((id) => {
        if (!templateChillerIdsObserved.has(id)) {
          finalTasks.push({ id, name: id, type: "asset", isCompleted: false, status: "Open" });
        }
      });

      const logMasterEntries = await db.select().from(logMaster).where(eq(logMaster.log_name, "Chiller Logs"));
      const sequenceMap = new Map<string, number>();
      logMasterEntries.forEach(entry => sequenceMap.set(entry.task_name, entry.sequence_number));

      return finalTasks.sort((a, b) => {
        const seqA = sequenceMap.get(a.name) ?? 999;
        const seqB = sequenceMap.get(b.name) ?? 999;
        if (seqA !== seqB) return seqA - seqB;
        return a.name.localeCompare(b.name);
      });
    } catch (error: any) {
      logger.error("Error fetching chiller tasks", { module: "SITE_CONFIG_SERVICE", error: error.message });
      return [];
    }
  },

  /**
   * Count pending days before/after the current date.
   * Simple: a day has pending tasks if there are non-Completed logs for that date.
   */
  async getPendingCountSummary(
    siteCode: string, 
    logName: string, 
    currentDate: string
  ): Promise<{ before: number, after: number }> {
    try {
      const logVariants = getLogVariants(logName);
      const parseDateStr = (s: string) => new Date(s);
      const formatDateStr = (d: Date) => d.toISOString().split("T")[0];

      const checkRange = async (days: number[]) => {
        let pendingDays = 0;
        for (const offset of days) {
          const target = formatDateStr(addDays(parseDateStr(currentDate), offset));
          const [result] = await db
            .select({ value: count() })
            .from(siteLogs)
            .where(
              and(
                eq(siteLogs.site_code, siteCode),
                inArray(siteLogs.log_name, logVariants),
                ne(siteLogs.status, "Completed"),
                sql`substr(${siteLogs.scheduled_date}, 1, 10) = ${target}`
              )
            );
          if (Number(result?.value || 0) > 0) {
            pendingDays++;
          }
        }
        return pendingDays;
      };

      const before = await checkRange([-1, -2, -3, -4, -5, -6, -7]);
      const after = await checkRange([1, 2, 3, 4, 5, 6, 7]);

      return { before, after };
    } catch (e: any) {
      logger.error("getPendingCountSummary failed", { siteCode, error: e.message });
      return { before: 0, after: 0 };
    }
  },

  /**
   * Count pending tasks for a specific date+shift. Already correct — kept as-is.
   */
  async getPendingCountForDate(siteCode: string, logName: string, scheduledDate: string, shift?: string): Promise<number> {
    try {
      const logVariants = getLogVariants(logName);

      const rows = await db
        .select({ id: siteLogs.id, remarks: siteLogs.remarks })
        .from(siteLogs)
        .where(
          and(
            eq(siteLogs.site_code, siteCode),
            inArray(siteLogs.log_name, logVariants),
            ne(siteLogs.status, "Completed"),
            sql`substr(${siteLogs.scheduled_date}, 1, 10) = ${scheduledDate}`
          )
        );

      if (!shift) return rows.length;
      const shiftMarker = shift === "A" ? "1/3" : shift === "B" ? "2/3" : shift === "C" ? "3/3" : null;
      if (!shiftMarker) return rows.length;
      return rows.filter((r) => r.remarks?.includes(shiftMarker)).length;
    } catch (e: any) {
      logger.error("getPendingCountForDate failed", { module: "SITE_CONFIG_SERVICE", error: e.message });
      return 0;
    }
  },

  async getGenericTask(siteCode: string, logName: string): Promise<TaskItem> {
    const start = startOfDay(new Date()).getTime();
    const end = endOfDay(new Date()).getTime();
    const result = await db.select({ value: count() }).from(siteLogs).where(and(eq(siteLogs.site_code, siteCode), eq(siteLogs.log_name, logName), or(ne(siteLogs.status, "Completed"), and(gte(siteLogs.created_at, start), lte(siteLogs.created_at, end)))));
    const logCount = result[0]?.value ?? 0;
    return { id: logName, name: logName === "Water" ? "Water Parameters" : `${logName} Log`, type: "general", isCompleted: logCount > 0, status: logCount > 0 ? "Completed" : "Open" };
  },
};
